[package]
name = "Nostalgic"
version = "0.1.0"
authors = ["Afonso Lage <lage.afonso@gmail.com>"]

[dependencies]

[lib]
name = "network"
path = "src/network/lib.rs"

[[bin]]
name = "cs"
path = "src/cs/main.rs"

[[bin]]
name = "gs"
path = "src/gs/main.rs"