[package]
name = "lcgs"
version = "0.1.0"
authors = ["Afonso Lage <lage.afonso@gmail.com>"]

[dependencies]
scheduled-executor = "*"
config = "*"
futures = "*"
tokio-io = "*"
tokio-core = "*"
failure = "*"
failure_derive = "*"
mu-proto = { path = "../../lib/mu-proto" }