[general]
server_code = 1
max_user = 100

[network]
listen_port = 55590
listen_addr = "0.0.0.0"
cs_addr = "127.0.0.1"
cs_port = 55557

[database]
url = "Server=127.0.0.1;Database=LCMU;Uid=usr_mu;Pwd=123456;"
